language: python

python:
  - 3.6

install:
  - npm install
  - pip install -r requirements.txt

before_script:
  - cd ..
  - git clone https://github.com/ucldc/exhibitapp.git
  - cd exhibitapp
  - pip install -r requirements.txt
  - cd ../public_interface
  - ln -s ../exhibitapp/exhibits/
  - export BOTO_CONFIG=/dev/null # https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
  - python manage.py migrate --noinput
  - python manage.py loaddata exhibits/fixtures/exhibits-2019-12-18-migrate-exhibits.json
  - npx gulp
  - python manage.py collectstatic --noinput
  - python manage.py runserver &
  - npx gulp serve &

script:
  - npm run pa11yci
  # - python manage.py test
