language: python

python:
  - 3.6

install:
  - npm install
  - pip install -r requirements.txt

before_script:
  - cd ..
  - git clone https://github.com/ucldc/exhibitapp.git
  - cd exhibitapp
  - pip install -r requirements.txt
  - cd ../public_interface
  - ln -s ../exhibitapp/exhibits/

# https://github.com/travis-ci/travis-ci/issues/7940#issuecomment-311411559
script:
  - export BOTO_CONFIG=/dev/null
  - npx gulp
  - python manage.py collectstatic --noinput
  # - python manage.py test
